-- ============================================================
-- UJ3DMap — Initial PostGIS Database Schema
-- Migration 001
-- Run against: self-hosted PostgreSQL with PostGIS extension
--
-- To apply:
--   psql -U postgres -d uj3dmap -f 001_initial.sql
-- ============================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS postgis;         -- Spatial geometry types and functions
CREATE EXTENSION IF NOT EXISTS vector;          -- pgvector for semantic search embeddings

-- ─── Users ───────────────────────────────────────────────────────────────────
-- Stores admin and helper accounts.
-- Passwords are stored as scrypt hashes (see authController.js).
-- JWT authentication — no sessions table needed.

CREATE TABLE IF NOT EXISTS users (
    id            UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    email         TEXT        NOT NULL UNIQUE,
    password_hash TEXT        NOT NULL,
    role          TEXT        NOT NULL DEFAULT 'helper'
                              CHECK (role IN ('admin', 'helper')),
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Buildings ───────────────────────────────────────────────────────────────
-- Polygon footprints of campus buildings.
-- geom stores the actual polygon boundary in WGS 84 (EPSG:4326).
-- height is stored for Phase 2 3D extrusion in MapLibre.

CREATE TABLE IF NOT EXISTS buildings (
    id          UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    name        TEXT         NOT NULL,
    campus      TEXT         NOT NULL CHECK (campus IN ('main', 'permanent', 'city')),
    category    TEXT         NOT NULL,  -- 'faculty', 'admin', 'hostel', 'amenity', 'library', 'service'
    description TEXT,
    height      NUMERIC(6,2) DEFAULT 0, -- metres, for 3D extrusion
    geom        GEOMETRY(MultiPolygon, 4326) NOT NULL,
    created_at  TIMESTAMPTZ  DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  DEFAULT NOW()
);

-- Spatial index: accelerates all ST_DWithin / ST_Intersects queries on buildings
CREATE INDEX IF NOT EXISTS buildings_geom_idx ON buildings USING GIST (geom);
-- Non-spatial index: filtering by campus is a very common query
CREATE INDEX IF NOT EXISTS buildings_campus_idx ON buildings (campus);

-- ─── Points of Interest (POIs) ───────────────────────────────────────────────
-- Single-point features: entrances, kiosks, ATMs, benches, etc.
-- embedding stores a 384-dimensional vector for semantic (natural language) search.
-- The embedding is generated by all-MiniLM-L6-v2 or equivalent.

CREATE TABLE IF NOT EXISTS pois (
    id              UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    name            TEXT         NOT NULL,
    campus          TEXT         NOT NULL CHECK (campus IN ('main', 'permanent', 'city')),
    category        TEXT         NOT NULL,
    description     TEXT,
    photo_day_url   TEXT,
    photo_night_url TEXT,
    floor_level     INTEGER      DEFAULT 0,
    building_id     UUID         REFERENCES buildings(id) ON DELETE SET NULL,
    geom            GEOMETRY(Point, 4326) NOT NULL,
    embedding       VECTOR(384),   -- For pgvector cosine-similarity semantic search
    created_at      TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS pois_geom_idx      ON pois USING GIST (geom);
CREATE INDEX IF NOT EXISTS pois_campus_idx    ON pois (campus);
-- IVFFlat index for approximate nearest-neighbour vector search
-- Lists = sqrt(row_count). Rebuild when the table grows significantly.
CREATE INDEX IF NOT EXISTS pois_embedding_idx ON pois USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 50);

-- ─── Paths (Routing Network Edges) ───────────────────────────────────────────
-- LineString geometries representing walkways, roads, and indoor corridors.
-- allowed_modes controls which travel modes can use each edge.
-- The routing service (GraphHopper) uses its own OSM-derived network;
-- this table stores supplementary campus-internal paths for indoor routing.

CREATE TABLE IF NOT EXISTS paths (
    id            UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    name          TEXT         NOT NULL,
    campus        TEXT         NOT NULL CHECK (campus IN ('main', 'permanent', 'city')),
    allowed_modes TEXT[]       NOT NULL DEFAULT '{"pedestrian","bicycle","vehicle"}',
    is_indoor     BOOLEAN      DEFAULT FALSE,
    floor_level   INTEGER,
    building_id   UUID         REFERENCES buildings(id) ON DELETE SET NULL,
    geom          GEOMETRY(LineString, 4326) NOT NULL,
    created_at    TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS paths_geom_idx    ON paths USING GIST (geom);
CREATE INDEX IF NOT EXISTS paths_campus_idx  ON paths (campus);

-- ─── Heatmaps (Crowdsourced Data Points) ─────────────────────────────────────
-- Individual user reports for Wi-Fi, power, crowd density, and parking.
-- Aggregated hourly by a batch job into density values the frontend renders.

CREATE TABLE IF NOT EXISTS heatmaps (
    id          UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    type        TEXT         NOT NULL CHECK (type IN ('wifi', 'power', 'crowd', 'parking')),
    intensity   INTEGER      NOT NULL CHECK (intensity BETWEEN 1 AND 10),
    reported_by UUID         REFERENCES users(id) ON DELETE SET NULL,
    geom        GEOMETRY(Point, 4326) NOT NULL,
    created_at  TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS heatmaps_geom_idx  ON heatmaps USING GIST (geom);
CREATE INDEX IF NOT EXISTS heatmaps_type_idx  ON heatmaps (type);
CREATE INDEX IF NOT EXISTS heatmaps_time_idx  ON heatmaps (created_at DESC);

-- ─── Video Guides ─────────────────────────────────────────────────────────────
-- Metadata for navigation walkthrough videos.
-- Actual video files live in object storage (S3/R2/Supabase Storage).
-- status must be 'approved' before the frontend shows the video.

CREATE TABLE IF NOT EXISTS video_guides (
    id                  UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    start_poi_id        UUID         REFERENCES pois(id) ON DELETE CASCADE,
    end_poi_id          UUID         REFERENCES pois(id) ON DELETE CASCADE,
    video_storage_url   TEXT         NOT NULL,
    thumbnail_url       TEXT,
    duration_seconds    INTEGER,
    status              TEXT         NOT NULL DEFAULT 'pending'
                                     CHECK (status IN ('pending', 'approved', 'rejected')),
    uploaded_by         UUID         REFERENCES users(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ  DEFAULT NOW()
);

-- ─── GeoJSON Import Log ───────────────────────────────────────────────────────
-- Audits every bulk import performed via the admin /api/admin/import endpoint.

CREATE TABLE IF NOT EXISTS import_log (
    id            UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    imported_by   UUID         REFERENCES users(id) ON DELETE SET NULL,
    feature_count INTEGER      NOT NULL,
    notes         TEXT,
    created_at    TIMESTAMPTZ  DEFAULT NOW()
);

-- ─── Trigger: auto-update updated_at on buildings ─────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER buildings_updated_at
  BEFORE UPDATE ON buildings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── Default admin account ───────────────────────────────────────────────────
-- Password: 'changeme_on_first_login'
-- Hash generated with: crypto.scryptSync('changeme_on_first_login', 'salt', 64).toString('hex')
-- IMPORTANT: Change this immediately after first deployment.
INSERT INTO users (email, password_hash, role)
VALUES (
  'admin@unijos.edu.ng',
  'REPLACE_WITH_SCRYPT_HASH',
  'admin'
) ON CONFLICT (email) DO NOTHING;
