const fs = require('fs');
const path = require('path');

function walk(dir) {
  let results = [];
  if (!fs.existsSync(dir)) return results;
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    let fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    if (stat && stat.isDirectory()) {
      results = results.concat(walk(fullPath));
    } else if (file.endsWith('.tsx') || file.endsWith('.ts')) {
      results.push(fullPath);
    }
  });
  return results;
}

const dirToProcess = process.argv[2];
if (!dirToProcess) {
  console.log("Please provide a directory or file");
  process.exit(1);
}

let files = [];
const stat = fs.statSync(dirToProcess);
if (stat.isDirectory()) {
  files = walk(dirToProcess);
} else {
  files = [dirToProcess];
}

files.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let original = content;
  
  // 1. Remove dark: prefix specifically targeting color utilities.
  //    Matches dark:bg-..., dark:text-..., dark:border-..., dark:ring-...
  content = content.replace(/dark:(bg|text|border|ring)-[a-zA-Z0-9_-]+/g, '');

  // 2. Replace light mode explicit colors with semantic alternatives.
  // Background colors
  content = content.replace(/\bbg-(?:slate|stone|gray|zinc|neutral)-(?:50|100|200)\b/g, 'bg-background');
  content = content.replace(/\bbg-white\b/g, 'bg-card');
  content = content.replace(/\bbg-(?:slate|stone|gray|zinc|neutral)-(?:700|800|900|950)\b/g, 'bg-foreground text-background');

  // Text Colors
  content = content.replace(/\btext-(?:slate|stone|gray|zinc|neutral)-(?:800|900|950)\b/g, 'text-foreground');
  content = content.replace(/\btext-(?:slate|stone|gray|zinc|neutral)-(?:600|700)\b/g, 'text-foreground/80');
  content = content.replace(/\btext-(?:slate|stone|gray|zinc|neutral)-(?:400|500)\b/g, 'text-muted-foreground');
  content = content.replace(/\btext-(?:slate|stone|gray|zinc|neutral)-(?:50|100|200|300)\b/g, 'text-background/80');

  // Placeholders
  content = content.replace(/\bplaceholder-(?:slate|stone|gray|zinc|neutral)-(?:400|500|600)\b/g, 'placeholder:text-muted-foreground');
  content = content.replace(/\btext-white\b/g, 'text-background');
  content = content.replace(/\btext-black\b/g, 'text-foreground');

  content = content.replace(/\bborder-(?:slate|stone|gray|zinc|neutral)-(?:200|300|100|50|700|800)\b/g, 'border-border');

  // Fix up any double spaces generated by removing `dark:` rules.
  content = content.replace(/ {2,}/g, ' ');

  if (content !== original) {
    fs.writeFileSync(file, content, 'utf8');
    console.log(`Updated ${file}`);
  }
});
